/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthAppRouteImport } from './routes/_auth/_app'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/_app/index'
import { Route as AuthAppAnalyticsRouteImport } from './routes/_auth/_app/analytics'
import { Route as AuthAppTranscriptionsRouteImport } from './routes/_auth/_app/transcriptions'
import { Route as AuthAppUploadFileRouteImport } from './routes/_auth/_app/upload-file'
import { Route as AuthAppUploadsRouteImport } from './routes/_auth/_app/uploads'
import { Route as AuthAppOrganisationsOrganisationIdRouteImport } from './routes/_auth/_app/organisations/$organisationId'
import { Route as AuthAppOrganisationsOrganisationIdIndexRouteImport } from './routes/_auth/_app/organisations/$organisationId/index'
import { Route as AuthAppOrganisationsOrganisationIdAnalyticsRouteImport } from './routes/_auth/_app/organisations/$organisationId/analytics'
import { Route as AuthAppOrganisationsOrganisationIdTranscriptionsRouteImport } from './routes/_auth/_app/organisations/$organisationId/transcriptions'
import { Route as AuthAppOrganisationsOrganisationIdUploadFileRouteImport } from './routes/_auth/_app/organisations/$organisationId/upload-file'
import { Route as AuthAppOrganisationsOrganisationIdUploadsRouteImport } from './routes/_auth/_app/organisations/$organisationId/uploads'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRoute = AuthAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppAnalyticsRoute = AuthAppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppTranscriptionsRoute = AuthAppTranscriptionsRouteImport.update({
  id: '/transcriptions',
  path: '/transcriptions',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppUploadFileRoute = AuthAppUploadFileRouteImport.update({
  id: '/upload-file',
  path: '/upload-file',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppUploadsRoute = AuthAppUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppOrganisationsOrganisationIdRoute =
  AuthAppOrganisationsOrganisationIdRouteImport.update({
    id: '/organisations/$organisationId',
    path: '/organisations/$organisationId',
    getParentRoute: () => AuthAppRoute,
  } as any)
const AuthAppOrganisationsOrganisationIdIndexRoute =
  AuthAppOrganisationsOrganisationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthAppOrganisationsOrganisationIdRoute,
  } as any)
const AuthAppOrganisationsOrganisationIdAnalyticsRoute =
  AuthAppOrganisationsOrganisationIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthAppOrganisationsOrganisationIdRoute,
  } as any)
const AuthAppOrganisationsOrganisationIdTranscriptionsRoute =
  AuthAppOrganisationsOrganisationIdTranscriptionsRouteImport.update({
    id: '/transcriptions',
    path: '/transcriptions',
    getParentRoute: () => AuthAppOrganisationsOrganisationIdRoute,
  } as any)
const AuthAppOrganisationsOrganisationIdUploadFileRoute =
  AuthAppOrganisationsOrganisationIdUploadFileRouteImport.update({
    id: '/upload-file',
    path: '/upload-file',
    getParentRoute: () => AuthAppOrganisationsOrganisationIdRoute,
  } as any)
const AuthAppOrganisationsOrganisationIdUploadsRoute =
  AuthAppOrganisationsOrganisationIdUploadsRouteImport.update({
    id: '/uploads',
    path: '/uploads',
    getParentRoute: () => AuthAppOrganisationsOrganisationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthAppIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/analytics': typeof AuthAppAnalyticsRoute
  '/transcriptions': typeof AuthAppTranscriptionsRoute
  '/upload-file': typeof AuthAppUploadFileRoute
  '/uploads': typeof AuthAppUploadsRoute
  '/organisations/$organisationId': typeof AuthAppOrganisationsOrganisationIdRouteWithChildren
  '/organisations/$organisationId/analytics': typeof AuthAppOrganisationsOrganisationIdAnalyticsRoute
  '/organisations/$organisationId/transcriptions': typeof AuthAppOrganisationsOrganisationIdTranscriptionsRoute
  '/organisations/$organisationId/upload-file': typeof AuthAppOrganisationsOrganisationIdUploadFileRoute
  '/organisations/$organisationId/uploads': typeof AuthAppOrganisationsOrganisationIdUploadsRoute
  '/organisations/$organisationId/': typeof AuthAppOrganisationsOrganisationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthAppIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/analytics': typeof AuthAppAnalyticsRoute
  '/transcriptions': typeof AuthAppTranscriptionsRoute
  '/upload-file': typeof AuthAppUploadFileRoute
  '/uploads': typeof AuthAppUploadsRoute
  '/organisations/$organisationId/analytics': typeof AuthAppOrganisationsOrganisationIdAnalyticsRoute
  '/organisations/$organisationId/transcriptions': typeof AuthAppOrganisationsOrganisationIdTranscriptionsRoute
  '/organisations/$organisationId/upload-file': typeof AuthAppOrganisationsOrganisationIdUploadFileRoute
  '/organisations/$organisationId/uploads': typeof AuthAppOrganisationsOrganisationIdUploadsRoute
  '/organisations/$organisationId': typeof AuthAppOrganisationsOrganisationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/_app': typeof AuthAppRouteWithChildren
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/_app/analytics': typeof AuthAppAnalyticsRoute
  '/_auth/_app/transcriptions': typeof AuthAppTranscriptionsRoute
  '/_auth/_app/upload-file': typeof AuthAppUploadFileRoute
  '/_auth/_app/uploads': typeof AuthAppUploadsRoute
  '/_auth/_app/': typeof AuthAppIndexRoute
  '/_auth/_app/organisations/$organisationId': typeof AuthAppOrganisationsOrganisationIdRouteWithChildren
  '/_auth/_app/organisations/$organisationId/analytics': typeof AuthAppOrganisationsOrganisationIdAnalyticsRoute
  '/_auth/_app/organisations/$organisationId/transcriptions': typeof AuthAppOrganisationsOrganisationIdTranscriptionsRoute
  '/_auth/_app/organisations/$organisationId/upload-file': typeof AuthAppOrganisationsOrganisationIdUploadFileRoute
  '/_auth/_app/organisations/$organisationId/uploads': typeof AuthAppOrganisationsOrganisationIdUploadsRoute
  '/_auth/_app/organisations/$organisationId/': typeof AuthAppOrganisationsOrganisationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/analytics'
    | '/transcriptions'
    | '/upload-file'
    | '/uploads'
    | '/organisations/$organisationId'
    | '/organisations/$organisationId/analytics'
    | '/organisations/$organisationId/transcriptions'
    | '/organisations/$organisationId/upload-file'
    | '/organisations/$organisationId/uploads'
    | '/organisations/$organisationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/analytics'
    | '/transcriptions'
    | '/upload-file'
    | '/uploads'
    | '/organisations/$organisationId/analytics'
    | '/organisations/$organisationId/transcriptions'
    | '/organisations/$organisationId/upload-file'
    | '/organisations/$organisationId/uploads'
    | '/organisations/$organisationId'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/_app'
    | '/_auth/onboarding'
    | '/_auth/_app/analytics'
    | '/_auth/_app/transcriptions'
    | '/_auth/_app/upload-file'
    | '/_auth/_app/uploads'
    | '/_auth/_app/'
    | '/_auth/_app/organisations/$organisationId'
    | '/_auth/_app/organisations/$organisationId/analytics'
    | '/_auth/_app/organisations/$organisationId/transcriptions'
    | '/_auth/_app/organisations/$organisationId/upload-file'
    | '/_auth/_app/organisations/$organisationId/uploads'
    | '/_auth/_app/organisations/$organisationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_app': {
      id: '/_auth/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthAppRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_app/': {
      id: '/_auth/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/_app/analytics': {
      id: '/_auth/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthAppAnalyticsRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/_app/transcriptions': {
      id: '/_auth/_app/transcriptions'
      path: '/transcriptions'
      fullPath: '/transcriptions'
      preLoaderRoute: typeof AuthAppTranscriptionsRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/_app/upload-file': {
      id: '/_auth/_app/upload-file'
      path: '/upload-file'
      fullPath: '/upload-file'
      preLoaderRoute: typeof AuthAppUploadFileRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/_app/uploads': {
      id: '/_auth/_app/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof AuthAppUploadsRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/_app/organisations/$organisationId': {
      id: '/_auth/_app/organisations/$organisationId'
      path: '/organisations/$organisationId'
      fullPath: '/organisations/$organisationId'
      preLoaderRoute: typeof AuthAppOrganisationsOrganisationIdRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/_app/organisations/$organisationId/': {
      id: '/_auth/_app/organisations/$organisationId/'
      path: '/'
      fullPath: '/organisations/$organisationId/'
      preLoaderRoute: typeof AuthAppOrganisationsOrganisationIdIndexRouteImport
      parentRoute: typeof AuthAppOrganisationsOrganisationIdRoute
    }
    '/_auth/_app/organisations/$organisationId/analytics': {
      id: '/_auth/_app/organisations/$organisationId/analytics'
      path: '/analytics'
      fullPath: '/organisations/$organisationId/analytics'
      preLoaderRoute: typeof AuthAppOrganisationsOrganisationIdAnalyticsRouteImport
      parentRoute: typeof AuthAppOrganisationsOrganisationIdRoute
    }
    '/_auth/_app/organisations/$organisationId/transcriptions': {
      id: '/_auth/_app/organisations/$organisationId/transcriptions'
      path: '/transcriptions'
      fullPath: '/organisations/$organisationId/transcriptions'
      preLoaderRoute: typeof AuthAppOrganisationsOrganisationIdTranscriptionsRouteImport
      parentRoute: typeof AuthAppOrganisationsOrganisationIdRoute
    }
    '/_auth/_app/organisations/$organisationId/upload-file': {
      id: '/_auth/_app/organisations/$organisationId/upload-file'
      path: '/upload-file'
      fullPath: '/organisations/$organisationId/upload-file'
      preLoaderRoute: typeof AuthAppOrganisationsOrganisationIdUploadFileRouteImport
      parentRoute: typeof AuthAppOrganisationsOrganisationIdRoute
    }
    '/_auth/_app/organisations/$organisationId/uploads': {
      id: '/_auth/_app/organisations/$organisationId/uploads'
      path: '/uploads'
      fullPath: '/organisations/$organisationId/uploads'
      preLoaderRoute: typeof AuthAppOrganisationsOrganisationIdUploadsRouteImport
      parentRoute: typeof AuthAppOrganisationsOrganisationIdRoute
    }
  }
}

interface AuthAppOrganisationsOrganisationIdRouteChildren {
  AuthAppOrganisationsOrganisationIdAnalyticsRoute: typeof AuthAppOrganisationsOrganisationIdAnalyticsRoute
  AuthAppOrganisationsOrganisationIdTranscriptionsRoute: typeof AuthAppOrganisationsOrganisationIdTranscriptionsRoute
  AuthAppOrganisationsOrganisationIdUploadFileRoute: typeof AuthAppOrganisationsOrganisationIdUploadFileRoute
  AuthAppOrganisationsOrganisationIdUploadsRoute: typeof AuthAppOrganisationsOrganisationIdUploadsRoute
  AuthAppOrganisationsOrganisationIdIndexRoute: typeof AuthAppOrganisationsOrganisationIdIndexRoute
}

const AuthAppOrganisationsOrganisationIdRouteChildren: AuthAppOrganisationsOrganisationIdRouteChildren =
  {
    AuthAppOrganisationsOrganisationIdAnalyticsRoute:
      AuthAppOrganisationsOrganisationIdAnalyticsRoute,
    AuthAppOrganisationsOrganisationIdTranscriptionsRoute:
      AuthAppOrganisationsOrganisationIdTranscriptionsRoute,
    AuthAppOrganisationsOrganisationIdUploadFileRoute:
      AuthAppOrganisationsOrganisationIdUploadFileRoute,
    AuthAppOrganisationsOrganisationIdUploadsRoute:
      AuthAppOrganisationsOrganisationIdUploadsRoute,
    AuthAppOrganisationsOrganisationIdIndexRoute:
      AuthAppOrganisationsOrganisationIdIndexRoute,
  }

const AuthAppOrganisationsOrganisationIdRouteWithChildren =
  AuthAppOrganisationsOrganisationIdRoute._addFileChildren(
    AuthAppOrganisationsOrganisationIdRouteChildren,
  )

interface AuthAppRouteChildren {
  AuthAppAnalyticsRoute: typeof AuthAppAnalyticsRoute
  AuthAppTranscriptionsRoute: typeof AuthAppTranscriptionsRoute
  AuthAppUploadFileRoute: typeof AuthAppUploadFileRoute
  AuthAppUploadsRoute: typeof AuthAppUploadsRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppOrganisationsOrganisationIdRoute: typeof AuthAppOrganisationsOrganisationIdRouteWithChildren
}

const AuthAppRouteChildren: AuthAppRouteChildren = {
  AuthAppAnalyticsRoute: AuthAppAnalyticsRoute,
  AuthAppTranscriptionsRoute: AuthAppTranscriptionsRoute,
  AuthAppUploadFileRoute: AuthAppUploadFileRoute,
  AuthAppUploadsRoute: AuthAppUploadsRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppOrganisationsOrganisationIdRoute:
    AuthAppOrganisationsOrganisationIdRouteWithChildren,
}

const AuthAppRouteWithChildren =
  AuthAppRoute._addFileChildren(AuthAppRouteChildren)

interface AuthRouteChildren {
  AuthAppRoute: typeof AuthAppRouteWithChildren
  AuthOnboardingRoute: typeof AuthOnboardingRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAppRoute: AuthAppRouteWithChildren,
  AuthOnboardingRoute: AuthOnboardingRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
