export const ApiErrorCode = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  INVALID_REQUEST: "INVALID_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  ORGANISATION_NOT_FOUND: "ORGANISATION_NOT_FOUND",
  ORGANISATION_FORBIDDEN: "ORGANISATION_FORBIDDEN",
  ORGANISATION_MEMBER_NOT_FOUND: "ORGANISATION_MEMBER_NOT_FOUND",
  ORGANISATION_MEMBER_USER_NOT_FOUND: "ORGANISATION_MEMBER_USER_NOT_FOUND",
  ORGANISATION_MEMBER_ALREADY_EXISTS: "ORGANISATION_MEMBER_ALREADY_EXISTS",
  ORGANISATION_OWNER_IMMUTABLE: "ORGANISATION_OWNER_IMMUTABLE",
  TRANSCRIPTION_NOT_FOUND: "TRANSCRIPTION_NOT_FOUND",
  TRANSCRIPTION_UPLOAD_NOT_FOUND: "TRANSCRIPTION_UPLOAD_NOT_FOUND",
} as const;

export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];

export type ApiErrorResponse<
  TApiErrorCode extends ApiErrorCode = ApiErrorCode,
  TMetadata extends Record<string, unknown> = Record<string, unknown>,
> = {
  errorCode: TApiErrorCode;
  message: string;
  metadata?: TMetadata;
};
